export const productsData = [
  {
    id: 'P101',
    name: 'Cash Counter Machine',
    quantity: '12',
    description:
      'Automatic currency counting machines used at teller counters.',
    amount: '25000',
    purchaseDate: '2025-02-01',
    category: 'Machine',
  },
  {
    id: 'P102',
    name: 'Note Sorting Machine',
    quantity: '6',
    description: 'Machine that detects fake notes and sorts denominations.',
    amount: '78000',
    purchaseDate: '2025-01-20',
    category: 'Machine',
  },
  {
    id: 'P103',
    name: 'Queue Token Dispenser',
    quantity: '3',
    description: 'Touchscreen token machine for customer queue management.',
    amount: '45000',
    purchaseDate: '2025-01-12',
    category: 'Machine',
  },
  {
    id: 'P104',
    name: 'Security Camera',
    quantity: '25',
    description: 'High-resolution surveillance cameras for banking halls.',
    amount: '9600',
    purchaseDate: '2025-02-02',
    category: 'Security',
  },
  {
    id: 'P105',
    name: 'Cheque Envelopes',
    quantity: '1500',
    description: 'Printed envelopes for cheque delivery to customers.',
    amount: '12',
    purchaseDate: '2025-01-28',
    category: 'Stationery',
  },
  {
    id: 'P106',
    name: 'Deposit Slip Book',
    quantity: '700',
    description: 'Printed deposit slip booklets for customer deposits.',
    amount: '20',
    purchaseDate: '2025-01-22',
    category: 'Stationery',
  },
  {
    id: 'P107',
    name: 'POS Machine',
    quantity: '18',
    description: 'Point-of-sale machines for merchants.',
    amount: '14500',
    purchaseDate: '2025-01-27',
    category: 'Machine',
  },
  {
    id: 'P108',
    name: 'Biometric Scanner',
    quantity: '10',
    description: 'Fingerprint scanners for customer verification.',
    amount: '3200',
    purchaseDate: '2025-01-18',
    category: 'Electronics',
  },
  {
    id: 'P109',
    name: 'Fingerprint Attendance Device',
    quantity: '5',
    description: 'Device used for employee check-in and check-out.',
    amount: '8200',
    purchaseDate: '2025-01-10',
    category: 'Electronics',
  },
  {
    id: 'P110',
    name: 'Token Display Screen',
    quantity: '8',
    description: 'LED display for queue management.',
    amount: '15500',
    purchaseDate: '2025-01-05',
    category: 'Electronics',
  },
  {
    id: 'P111',
    name: 'A4 Printing Paper',
    quantity: '3000',
    description: 'Paper reams for printing statements and documents.',
    amount: '6',
    purchaseDate: '2025-01-14',
    category: 'Stationery',
  },
  {
    id: 'P112',
    name: 'Stapler Machine',
    quantity: '60',
    description: 'Heavy-duty staplers used at teller counters.',
    amount: '140',
    purchaseDate: '2025-01-07',
    category: 'Stationery',
  },
  {
    id: 'P113',
    name: 'Ink Cartridges',
    quantity: '120',
    description: 'Ink cartridges for branch printers.',
    amount: '350',
    purchaseDate: '2025-01-03',
    category: 'Stationery',
  },
  {
    id: 'P114',
    name: 'Laser Printer',
    quantity: '20',
    description: 'High-speed laser printers for bank operations.',
    amount: '12500',
    purchaseDate: '2025-01-11',
    category: 'Electronics',
  },
  {
    id: 'P115',
    name: 'CCTV DVR System',
    quantity: '12',
    description: 'Recording system for surveillance cameras.',
    amount: '18000',
    purchaseDate: '2025-01-04',
    category: 'Security',
  },
  {
    id: 'P116',
    name: 'Router',
    quantity: '25',
    description: 'High-speed routers for secure banking network.',
    amount: '4200',
    purchaseDate: '2025-02-03',
    category: 'IT',
  },
  {
    id: 'P117',
    name: 'Network Switch',
    quantity: '18',
    description: 'Gigabit switch for branch network.',
    amount: '8800',
    purchaseDate: '2025-02-01',
    category: 'IT',
  },
  {
    id: 'P118',
    name: 'Server Rack',
    quantity: '4',
    description: 'Rack for servers and networking equipment.',
    amount: '30500',
    purchaseDate: '2025-01-21',
    category: 'IT',
  },
  {
    id: 'P119',
    name: 'Cheque Printing Machine',
    quantity: '7',
    description: 'Machine used to print customer cheques securely.',
    amount: '16500',
    purchaseDate: '2025-01-25',
    category: 'Machine',
  },
  {
    id: 'P120',
    name: 'Cash Deposit Machine',
    quantity: '2',
    description: 'Self-service cash deposit machines.',
    amount: '220000',
    purchaseDate: '2025-01-30',
    category: 'Machine',
  },
  {
    id: 'P121',
    name: 'ATM Machine',
    quantity: '5',
    description: 'Automated teller machine for cash withdrawal.',
    amount: '450000',
    purchaseDate: '2025-01-09',
    category: 'Machine',
  },
  {
    id: 'P122',
    name: 'Office Chairs',
    quantity: '85',
    description: 'Ergonomic office chairs for staff.',
    amount: '3500',
    purchaseDate: '2025-01-13',
    category: 'Furniture',
  },
  {
    id: 'P123',
    name: 'Office Desk',
    quantity: '40',
    description: 'Wooden desks for staff workstations.',
    amount: '7500',
    purchaseDate: '2025-01-15',
    category: 'Furniture',
  },
  {
    id: 'P124',
    name: 'Projector',
    quantity: '5',
    description: 'Used in conference rooms for presentations.',
    amount: '12000',
    purchaseDate: '2025-01-17',
    category: 'Electronics',
  },
  {
    id: 'P125',
    name: 'Whiteboard',
    quantity: '12',
    description: 'Whiteboards for meeting rooms and training halls.',
    amount: '1800',
    purchaseDate: '2025-01-19',
    category: 'Furniture',
  },
  {
    id: 'P126',
    name: 'Shredder Machine',
    quantity: '10',
    description: 'Used for secure disposal of sensitive documents.',
    amount: '5500',
    purchaseDate: '2025-01-20',
    category: 'Machine',
  },
  {
    id: 'P127',
    name: 'Telephone Set',
    quantity: '35',
    description: 'Landline phones for branch communication.',
    amount: '1200',
    purchaseDate: '2025-01-21',
    category: 'Electronics',
  },
  {
    id: 'P128',
    name: 'Staples Box',
    quantity: '200',
    description: 'Staples boxes for stapler machines.',
    amount: '50',
    purchaseDate: '2025-01-22',
    category: 'Stationery',
  },
  {
    id: 'P129',
    name: 'Pen Pack',
    quantity: '500',
    description: 'Ballpoint pens for branch use.',
    amount: '10',
    purchaseDate: '2025-01-23',
    category: 'Stationery',
  },
  {
    id: 'P130',
    name: 'Calculator',
    quantity: '20',
    description: 'Standard calculators for teller counters.',
    amount: '550',
    purchaseDate: '2025-01-24',
    category: 'Electronics',
  },
  {
    id: 'P131',
    name: 'Fire Extinguisher',
    quantity: '15',
    description: 'For branch safety and fire emergencies.',
    amount: '3000',
    purchaseDate: '2025-01-25',
    category: 'Security',
  },
  {
    id: 'P132',
    name: 'First Aid Kit',
    quantity: '12',
    description: 'Basic medical supplies for branch use.',
    amount: '1500',
    purchaseDate: '2025-01-26',
    category: 'Security',
  },
  {
    id: 'P133',
    name: 'Network Firewall',
    quantity: '5',
    description: 'Hardware firewall for branch network security.',
    amount: '18000',
    purchaseDate: '2025-01-27',
    category: 'IT',
  },
  {
    id: 'P134',
    name: 'Laptop',
    quantity: '18',
    description: 'For staff workstations and branch operations.',
    amount: '65000',
    purchaseDate: '2025-01-28',
    category: 'Electronics',
  },
  {
    id: 'P135',
    name: 'Mouse & Keyboard Set',
    quantity: '50',
    description: 'Standard input devices for desktops.',
    amount: '1200',
    purchaseDate: '2025-01-29',
    category: 'IT',
  },
  {
    id: 'P136',
    name: 'Desk Lamp',
    quantity: '30',
    description: 'LED desk lamps for teller counters.',
    amount: '800',
    purchaseDate: '2025-01-30',
    category: 'Furniture',
  },
  {
    id: 'P137',
    name: 'UPS System',
    quantity: '12',
    description: 'Backup power for branch servers and ATMs.',
    amount: '15000',
    purchaseDate: '2025-01-31',
    category: 'IT',
  },
  {
    id: 'P138',
    name: 'Water Dispenser',
    quantity: '6',
    description: 'For staff and customer use in the branch.',
    amount: '4200',
    purchaseDate: '2025-02-01',
    category: 'Furniture',
  },
  {
    id: 'P139',
    name: 'Wall Clock',
    quantity: '20',
    description: 'Analog clocks for branch halls.',
    amount: '500',
    purchaseDate: '2025-02-02',
    category: 'Furniture',
  },
  {
    id: 'P140',
    name: 'Receipt Printer',
    quantity: '15',
    description: 'Printers used for customer receipts.',
    amount: '5500',
    purchaseDate: '2025-02-03',
    category: 'Electronics',
  },
  {
    id: 'P141',
    name: 'Branch Name Plate',
    quantity: '25',
    description: 'Official signage for branches.',
    amount: '300',
    purchaseDate: '2025-02-04',
    category: 'Stationery',
  },
  {
    id: 'P142',
    name: 'Document Tray',
    quantity: '40',
    description: 'Used for sorting customer files.',
    amount: '450',
    purchaseDate: '2025-02-05',
    category: 'Stationery',
  },
  {
    id: 'P143',
    name: 'Pen Stand',
    quantity: '30',
    description: 'Desk pen holders for staff counters.',
    amount: '200',
    purchaseDate: '2025-02-06',
    category: 'Furniture',
  },
  {
    id: 'P144',
    name: 'Binder Clips Pack',
    quantity: '150',
    description: 'Used to organize files and documents.',
    amount: '100',
    purchaseDate: '2025-02-07',
    category: 'Stationery',
  },
  {
    id: 'P145',
    name: 'Cash Bag',
    quantity: '10',
    description: 'Secure cash bags for transport.',
    amount: '900',
    purchaseDate: '2025-02-08',
    category: 'Security',
  },
  {
    id: 'P146',
    name: 'Visitor Chair',
    quantity: '50',
    description: 'Chairs for customers in waiting area.',
    amount: '1800',
    purchaseDate: '2025-02-09',
    category: 'Furniture',
  },
  {
    id: 'P147',
    name: 'Desktop Monitor',
    quantity: '25',
    description: 'LED monitors for staff desktops.',
    amount: '9500',
    purchaseDate: '2025-02-10',
    category: 'IT',
  },
  {
    id: 'P148',
    name: 'Sticky Notes Pack',
    quantity: '200',
    description: 'Used for reminders and notes at counters.',
    amount: '50',
    purchaseDate: '2025-02-11',
    category: 'Stationery',
  },
  {
    id: 'P149',
    name: 'Branch Notice Board',
    quantity: '10',
    description: 'Used to display official notices and circulars.',
    amount: '2500',
    purchaseDate: '2025-02-12',
    category: 'Furniture',
  },
  {
    id: 'P150',
    name: 'Key Cabinet',
    quantity: '5',
    description: 'For storing branch keys securely.',
    amount: '3200',
    purchaseDate: '2025-02-13',
    category: 'Security',
  },
];
