export const userData = [
  {
    id: 1,
    email: 'john.doe@example.com',
    firstName: 'John',
    lastName: 'Doe',
    location: 'Kathmandu',
    contact: '014410856',
  },
  {
    id: 2,
    email: 'seemran.m@example.com',
    firstName: 'Seemran',
    lastName: 'Maharjan',
    location: 'Lalitpur',
    contact: '014448921',
  },
  {
    id: 3,
    email: 'sophia.rai@example.com',
    firstName: 'Sophia',
    lastName: 'Rai',
    location: 'Bhaktapur',
    contact: '014411223',
  },
  {
    id: 4,
    email: 'milan.shrestha@example.com',
    firstName: 'Milan',
    lastName: 'Shrestha',
    location: 'Pokhara',
    contact: '014421563',
  },
  {
    id: 5,
    email: 'anisha.gurung@example.com',
    firstName: 'Anisha',
    lastName: 'Gurung',
    location: 'Butwal',
    contact: '014499874',
  },
];
